services:
  accounting:
    build:
      network: host
      context: .
    ports:
      - 9095:9095
      - 5005:5005
    networks:
      - accounting_net
    volumes:
      - ./accounting_data:/data

networks:
  accounting_net:
    driver: host